#!/bin/sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`
javac Interface.java
javah -jni Interface
gcc -I/etc/alternatives/java_sdk/include -I/etc/alternatives/java_sdk/include/linux -shared -fPIC -o libImpl.so Impl.cpp
javac Main.java
java Main

